# Generated by Django 5.0.1 on 2024-01-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
