# Generated by Django 5.0.1 on 2024-02-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_publication_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
